/**
 * Emits supabase/seed.sql from the shared demo catalog data, for pasting into
 * the Supabase SQL Editor when the network can't reach Supabase directly.
 *
 *   npm run seed:sql
 *
 * The generated file is idempotent-ish: it deletes existing dishes/restaurants
 * first, then re-inserts. Restaurants get deterministic UUIDs so dishes can
 * reference them without a round-trip.
 */
import { createHash } from "node:crypto";
import { writeFileSync, mkdirSync } from "node:fs";
import { IMAGES, restaurants, dishes } from "./seed-data";

// Deterministic v4-shaped UUID from a name, so restaurants and their dishes
// can be inserted in one script without reading generated ids back.
function uuidFrom(name: string): string {
  const h = createHash("sha256").update(name).digest("hex").slice(0, 32);
  const b = h.split("");
  b[12] = "4"; // version
  b[16] = ((parseInt(b[16], 16) & 0x3) | 0x8).toString(16); // variant
  const s = b.join("");
  return `${s.slice(0, 8)}-${s.slice(8, 12)}-${s.slice(12, 16)}-${s.slice(
    16,
    20
  )}-${s.slice(20, 32)}`;
}

const q = (s: string) => `'${s.replace(/'/g, "''")}'`;
const jsonb = (v: unknown) => `${q(JSON.stringify(v))}::jsonb`;
const textArray = (arr: string[]) =>
  arr.length === 0
    ? `'{}'::text[]`
    : `ARRAY[${arr.map(q).join(", ")}]::text[]`;

const lines: string[] = [];
lines.push("-- Demo catalog seed. Generated by scripts/gen-seed-sql.ts.");
lines.push("-- Safe to re-run: clears the catalog, then re-inserts.");
lines.push("begin;");
lines.push("delete from public.dishes;");
lines.push("delete from public.restaurants;");
lines.push("");

const idByName = new Map<string, string>();
lines.push(
  "insert into public.restaurants (id, name, area) values"
);
const rValues = restaurants.map((r) => {
  const id = uuidFrom(`restaurant:${r.name}`);
  idByName.set(r.name, id);
  return `  (${q(id)}, ${q(r.name)}, ${q(r.area)})`;
});
lines.push(rValues.join(",\n") + ";");
lines.push("");

lines.push(
  "insert into public.dishes (restaurant_id, name, image_url, price, description, attributes, cuisine, main_protein, prep_style, is_veg, is_halal, allergens, delivery_apps) values"
);
const dValues = dishes.map((d, i) => {
  const rid = idByName.get(d.restaurant);
  if (!rid) throw new Error(`Unknown restaurant: ${d.restaurant}`);
  return (
    "  (" +
    [
      q(rid),
      q(d.name),
      q(IMAGES[i % IMAGES.length]),
      String(d.price),
      q(d.description),
      jsonb(d.attributes),
      q(d.cuisine),
      q(d.main_protein),
      q(d.prep_style),
      d.is_veg ?? false,
      d.is_halal ?? true,
      textArray(d.allergens ?? []),
      jsonb(d.apps ?? []),
    ].join(", ") +
    ")"
  );
});
lines.push(dValues.join(",\n") + ";");
lines.push("");
lines.push("commit;");
lines.push("");

mkdirSync("supabase", { recursive: true });
writeFileSync("supabase/seed.sql", lines.join("\n"));
console.log(
  `Wrote supabase/seed.sql: ${restaurants.length} restaurants, ${dishes.length} dishes.`
);
